# Generated by Django 5.1.1 on 2024-12-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('College', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorInfo',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='导师编号')),
                ('password', models.CharField(max_length=128, verbose_name='用户密码')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='职称')),
                ('research_area', models.CharField(blank=True, max_length=50, null=True, verbose_name='研究方向')),
                ('description', models.TextField(blank=True, null=True, verbose_name='教师介绍')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.collegeinfo', verbose_name='学院编号')),
            ],
            options={
                'verbose_name': '导师信息',
                'verbose_name_plural': '导师信息列表',
            },
        ),
        migrations.CreateModel(
            name='TopicInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='课题编号')),
                ('name', models.CharField(max_length=30, verbose_name='课题名称')),
                ('research_area', models.CharField(max_length=50, verbose_name='研究方向')),
                ('max_len', models.IntegerField(default=1, verbose_name='最大人数')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='课题要求')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Mentor.mentorinfo', verbose_name='导师编号')),
            ],
            options={
                'verbose_name': '课题信息',
                'verbose_name_plural': '课题信息列表',
            },
        ),
    ]
