# Generated by Django 5.1.1 on 2024-12-10 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('College', '0001_initial'),
        ('Mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeAdminInfo',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='管理员编号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('password', models.CharField(max_length=128, verbose_name='用户密码')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='职称')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='College.collegeinfo', verbose_name='学院编号')),
            ],
            options={
                'verbose_name': '学院管理员信息',
                'verbose_name_plural': '学院管理员信息列表',
            },
        ),
        migrations.CreateModel(
            name='TopicReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='审核日期')),
                ('status', models.IntegerField(choices=[(0, '待审核'), (1, '同意'), (2, '拒绝')], default=0, verbose_name='审核结果')),
                ('collegeAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_topic_reviews', to='CollegeAdmin.collegeadmininfo', verbose_name='管理员编号')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_reviews', to='Mentor.topicinfo', verbose_name='课题编号')),
            ],
            options={
                'verbose_name': '课题审核信息',
                'verbose_name_plural': '课题审核信息列表',
            },
        ),
    ]
